Guild.find_or_create_by_name('php', url_safe_name: 'php')
Guild.find_or_create_by_name('python', url_safe_name: 'python')
Guild.find_or_create_by_name('ruby', url_safe_name: 'ruby')
Guild.find_or_create_by_name('perl', url_safe_name: 'perl')
Guild.find_or_create_by_name('haskell', url_safe_name: 'haskell')
Guild.find_or_create_by_name('scala', url_safe_name: 'scala')
Guild.find_or_create_by_name('java', url_safe_name: 'java')
Guild.find_or_create_by_name('c', url_safe_name: 'c')
Guild.find_or_create_by_name('c++', url_safe_name: 'cpp')
Guild.find_or_create_by_name('c#', url_safe_name: 'csharp')
Guild.find_or_create_by_name('JavaScript', url_safe_name: 'js')
Guild.find_or_create_by_name('Objective C', url_safe_name: 'objectivec')
Guild.find_or_create_by_name('OCaml', url_safe_name: 'ocaml')
Guild.find_or_create_by_name('Pascal', url_safe_name: 'pascal')
