Guild.find_or_create_by(name: 'php', url_safe_name: 'php')
Guild.find_or_create_by(name: 'python', url_safe_name: 'python')
Guild.find_or_create_by(name: 'ruby', url_safe_name: 'ruby')
Guild.find_or_create_by(name: 'perl', url_safe_name: 'perl')
Guild.find_or_create_by(name: 'haskell', url_safe_name: 'haskell')
Guild.find_or_create_by(name: 'scala', url_safe_name: 'scala')
Guild.find_or_create_by(name: 'java', url_safe_name: 'java')
Guild.find_or_create_by(name: 'c', url_safe_name: 'c')
Guild.find_or_create_by(name: 'c++', url_safe_name: 'cpp')
Guild.find_or_create_by(name: 'c#', url_safe_name: 'csharp')
Guild.find_or_create_by(name: 'JavaScript', url_safe_name: 'js')
Guild.find_or_create_by(name: 'Objective C', url_safe_name: 'objectivec')
Guild.find_or_create_by(name: 'OCaml', url_safe_name: 'ocaml')
Guild.find_or_create_by(name: 'Pascal', url_safe_name: 'pascal')
