Guild.find_or_create_by(name: 'PHP', url_safe_name: 'php')
Guild.find_or_create_by(name: 'Python', url_safe_name: 'python')
Guild.find_or_create_by(name: 'Ruby', url_safe_name: 'ruby')
Guild.find_or_create_by(name: 'Perl', url_safe_name: 'perl')
Guild.find_or_create_by(name: 'Haskell', url_safe_name: 'haskell')
Guild.find_or_create_by(name: 'Scala', url_safe_name: 'scala')
Guild.find_or_create_by(name: 'Java', url_safe_name: 'java')
Guild.find_or_create_by(name: 'C', url_safe_name: 'c')
Guild.find_or_create_by(name: 'C++', url_safe_name: 'cpp')
Guild.find_or_create_by(name: 'C#', url_safe_name: 'csharp')
Guild.find_or_create_by(name: 'JavaScript', url_safe_name: 'js')
Guild.find_or_create_by(name: 'Objective C', url_safe_name: 'objectivec')
Guild.find_or_create_by(name: 'OCaml', url_safe_name: 'ocaml')
Guild.find_or_create_by(name: 'Pascal', url_safe_name: 'pascal')
