# -*- coding: utf-8 -*-
Quest.create!(creator_id: 1, title: 'prime', description: "素数")
Quest.create!(creator_id: 2, title: 'fibonacci', description: "フィボナッチ数列")
Quest.create!(creator_id: 2, title: 'dijakstra', description: "ダイクストラ法")
Quest.create!(creator_id: 6, title: 'overflow', description: "桁あふれ")
Quest.create!(creator_id: 6, title: 'bfs', description: "幅優先探索")
Quest.create!(creator_id: 5, title: 'dfs', description: "深さ優先探索")
Quest.create!(creator_id: 5, title: 'dp', description: "動的計画法")
Quest.create!(creator_id: 4, title: 'max_flow', description: "最大流量問題")
Quest.create!(creator_id: 4, title: 'MST', description: "最小全域木")
Quest.create!(creator_id: 4, title: 'Unionfind', description: "素集合データ構造")
