Code.create!(user_id: 1, guild_id: 1, quest_id: 1, source: "prime")
Code.create!(user_id: 2, guild_id: 2, quest_id: 2, source: "fibonacci")
Code.create!(user_id: 2, guild_id: 2, quest_id: 3, source: "dijakstra")
Code.create!(user_id: 6, guild_id: 6, quest_id: 4, source: "overflow")
Code.create!(user_id: 6, guild_id: 6, quest_id: 5, source: "bfs")
Code.create!(user_id: 5, guild_id: 5, quest_id: 6, source: "dfs")
Code.create!(user_id: 5, guild_id: 5, quest_id: 7, source: "dp")
Code.create!(user_id: 4, guild_id: 4, quest_id: 8, source: "max_flow")
Code.create!(user_id: 4, guild_id: 4, quest_id: 9, source: "MST")
Code.create!(user_id: 4, guild_id: 4, quest_id: 10, source: "Unionfind")

Code.create!(user_id: 2, guild_id: 2, quest_id: 1, source: "prime11")
Code.create!(user_id: 3, guild_id: 3, quest_id: 1, source: "prime22")
Code.create!(user_id: 4, guild_id: 4, quest_id: 1, source: "prime33")
Code.create!(user_id: 5, guild_id: 5, quest_id: 1, source: "prime44")
Code.create!(user_id: 6, guild_id: 6, quest_id: 1, source: "prime55")
Code.create!(user_id: 7, guild_id: 7, quest_id: 1, source: "prime66")
