development:
  adapter: sqlite3
  encoding: unicode
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: unicode
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: dmtc_development
  pool: 5
  timeout: 5000
  username: root
  password:
